# Generated by Django 5.2.6 on 2025-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_for_month",
            field=models.IntegerField(
                blank=True, help_text="Month number (1-12)", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_for_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
