# Generated by Django 5.2.6 on 2025-09-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_payment_payment_for_month_payment_payment_for_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(
                blank=True, null=True, upload_to="payment_receipts/"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
