# Generated by Django 5.2.6 on 2025-09-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_notes_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
