# Generated by Django 5.2.6 on 2025-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.AddField(
            model_name="amenity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="number_of_rooms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="rent_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="block",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estate",
            name="size",
            field=models.CharField(
                blank=True, help_text="e.g., 5 acres", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="furnishing",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="size",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Size in square meters",
                max_digits=5,
                null=True,
            ),
        ),
    ]
